### PR TITLE
Create heatmap smashing magazine

### PR DESCRIPTION
**Pull request by bren2102**
I kindly request a code review for this project. This project consists of building a heatmap of the [Smashing magazine](https://www.smashingmagazine.com/) website.

- Add nav bar
- Add header
- Add main section
- Add footer
- Add images spaces

### CODE REVIEW

**Comment by Anna-Myzukina** [comment]
### Pull Request under the review by Anna Muzykina (TSE)

**Comment by Anna-Myzukina** [comment]
### Hi team!
### Nice job! WOW, project looks! :+1: 

### But your project needs a few changes before it can be approved.

#### Page structure

##### Navigation bar


* It uses div and positions elements as at the source page (content is not important) ([link to page](https://www.smashingmagazine.com/))

##### 3 articles rows

* It contains 3 articles, each takes one third of the width (content is not important) ([link to page](https://www.smashingmagazine.com/))

In original version after 2 section row should be 3 section row


In your project instead of 3 section row now 1 section row


##### Footer

* It contains centered links (content is not important) ([link to page](https://www.smashingmagazine.com/))


### Make changes and submit another code review request.

*If you have any questions, let me know on slack (@Anna-Muzykina) and I will be glad to clarify with you.*

*Happy coding 😄*

**Comment by bren2102** [comment]
- Three div added on nav bar
- Three articles in a row on latest-posts section 
- Added links to the footer

**Comment by Anna-Myzukina** [comment]
### Nice job! Project looks! :100: 

## Status [Approved]


You have resolved all the issues!!!




#### Go ahead and merge to master.
#### Goodluck in your next project Happy coding

**Review by Anna-Myzukina — APPROVED** [review]

**Pull request merged**
